# Generated by Django 3.2.9 on 2021-11-25 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('09f9bfdf-9924-4160-b91e-48c7be560b0a'), max_length=1000),
        ),
    ]
