# Generated by Django 3.2.9 on 2021-11-26 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211125_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('8594c017-cdca-4cbf-a2c5-716ec4f1e818'), max_length=1000),
        ),
    ]
