# Generated by Django 3.2.9 on 2021-11-26 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('588e61a5-578d-4702-899b-4afeebc3e109'), max_length=1000),
        ),
    ]
