# Generated by Django 3.2.9 on 2021-12-01 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key',
            field=models.CharField(default=uuid.UUID('13603a1b-5554-42dc-8767-ce2bdcd8e6df'), max_length=1000),
        ),
    ]
